version: '3.5'
services:
  
  # Back-end
  express_api:
    container_name: express_api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: express_api
    user: node
    working_dir: /home/node/app/api
    volumes:
      - ${LOCAL_API_PATH}:/home/node/app
    ports:
      - 7770:7770
    depends_on:
      - database
    env_file:
      - ./api/.env

  # Front-end
  react_client:
    container_name: react_client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react_client
    working_dir: /home/node/app/client
    volumes:
      - ${LOCAL_CLIENT_PATH}:/home/node/app
    ports:
      - 7771:7771
    env_file:
      - ./client/.env

  # DB
  database:
    container_name: mongo_db
    image: mongo
    env_file:
      - ./api/.env